query all($id: string, $first: int = 10000, $offset: int = 0, $uri: string) {
  q(func: eq(uri, $uri)) {
    uid
    uri
    label
    rel @facets(label, edge_id) {
      uid
      uri
      label
    }
  }
}