query most_neighbors {
  q(func: type(Concept), orderdesc: neighbors_cnt, first: 10) {
    uid
    label
  	rel @facets {
      uid
      label
    }
  	outgoing_cnt
  	ingoing_cnt
		neighbors_cnt
  }
}