query single_neighbor($first: int = 10000, $offset: int = 0, $id: int) {
  var(func: eq(neighbors_cnt, 1)) {
    S as uid
  }

  total(func: uid(S)) {
    count(uid)
  }
  
  q(func: eq(neighbors_cnt, 1), first: $first) {
  	uid
  	label
  }
}