query grandparents($id: string, $first: int = 10000, $offset: int = 0) {
  q(func: uid($id)) {
    uid
    label
    ~rel @facets {
      uid
      label
      ~rel @facets {
        uid
        label
      }
    }
  }
}